type Item = {
    name: string;
    type: "weapon" | "armor" | "medicine" | "poison";
    effect: number;
    mind: number;
}

export const rpgItems: Item[] = [
        { name: "消える原子", type: "poison", effect: 85, mind: -50 },
        { name: "いにしえのチョコボ", type: "armor", effect: 70, mind: 60 },
        { name: "生のじゃがいも", type: "poison", effect: 60, mind: -30 },
        { name: "合法のペットボトルのキャップ", type: "weapon", effect: 10, mind: 5 },
        { name: "かわいいメガネ", type: "armor", effect: 40, mind: 70 },
        { name: "カビの生えたポップアップ広告", type: "poison", effect: 90, mind: -90 },
        { name: "デジタルブルーレイディスク", type: "weapon", effect: 30, mind: 5 },
        { name: "プレミア付き石像", type: "armor", effect: 80, mind: 40 },
        { name: "異世界のメビウスの輪", type: "weapon", effect: 70, mind: 50 },
        { name: "滅びのもぎもぎフルーツ", type: "poison", effect: 100, mind: -100 },
        { name: "等速直線運動する遠心分離機かつ焦げたちいさなメダル", type: "armor", effect: 30, mind: -10 },
        { name: "最強の消しゴム", type: "weapon", effect: 20, mind: 0 },
        { name: "ネザライトのメビウスの輪", type: "weapon", effect: 90, mind: 80 },
        { name: "耐火3getロボ", type: "armor", effect: 85, mind: 40 },
        { name: "もちもちラジオメーター", type: "armor", effect: 30, mind: 20 },
        { name: "幸運のエンチャントが付与された腰", type: "armor", effect: 60, mind: 90 },
        { name: "電動裁判所", type: "weapon", effect: 50, mind: -10 },
        { name: "ラスボスの本", type: "weapon", effect: 80, mind: 70 },
        { name: "ダイアモンドの[R]で所持金MAX の秘技コード", type: "weapon", effect: 95, mind: 90 },
        { name: "遺伝子組み換え炭水化物", type: "poison", effect: 75, mind: -40 },
        { name: "かわいい原子力発電所", type: "armor", effect: 70, mind: 60 },
        { name: "中古の愛", type: "poison", effect: 50, mind: -20 },
        { name: "チョコレートコーティング太陽", type: "weapon", effect: 85, mind: 70 },
        { name: "食用電子機器", type: "poison", effect: 80, mind: -70 },
        { name: "アルミホイルのラッピー", type: "weapon", effect: 35, mind: 0 },
        { name: "手作りブラックホール", type: "weapon", effect: 100, mind: 100 },
        { name: "鉄のバカデカメダル", type: "armor", effect: 90, mind: 50 },
        { name: "川を流れるカバのツルハシ", type: "weapon", effect: 60, mind: 20 },
        { name: "ピンクのチョコレート", type: "medicine", effect: 70, mind: 60 },
        { name: "ハート型のタコの足", type: "poison", effect: 55, mind: -40 },
        { name: "800kgくらいあるリップクリーム", type: "armor", effect: 20, mind: -20 },
        { name: "デジタルSSD", type: "weapon", effect: 25, mind: 0 },
        { name: "【令和最新版】水銀", type: "poison", effect: 95, mind: -80 },
        { name: "ココイチのカード状のもの", type: "medicine", effect: 20, mind: 15 },
        { name: "高度に訓練された水", type: "medicine", effect: 85, mind: 70 },
        { name: "時空を歪めるつまようじ", type: "weapon", effect: 75, mind: 70 },
        { name: "プラズマ化したなめこ", type: "poison", effect: 80, mind: -50 },
        { name: "ギガズッキーニ", type: "weapon", effect: 40, mind: 10 },
        { name: "リップクリームを虐げる群生するタコの足", type: "weapon", effect: 45, mind: -10 },
        { name: "次世代核融合炉", type: "armor", effect: 90, mind: 70 },
        { name: "燃え盛るDVD", type: "weapon", effect: 85, mind: 50 },
        { name: "小さな空気", type: "armor", effect: 10, mind: -10 },
        { name: "分散型オリハルコン", type: "armor", effect: 75, mind: 50 },
        { name: "無機質なボールペン", type: "weapon", effect: 35, mind: -5 },
        { name: "4次元四天王メンサの時計じかけの全知全能", type: "weapon", effect: 90, mind: 90 },
        { name: "粗挽き🤯", type: "poison", effect: 70, mind: -50 },
        { name: "ぐにゃぐにゃちいさなメダル", type: "armor", effect: 15, mind: -5 },
        { name: "折り畳み式サンドピクチャー", type: "armor", effect: 40, mind: 30 },
        { name: "時計じかけの空き缶", type: "weapon", effect: 20, mind: 5 },
        { name: "中古のフロッピーディスク", type: "weapon", effect: 10, mind: -10 },
        { name: "銅のCalckey", type: "weapon", effect: 30, mind: 5 },
        { name: "熟成月の石", type: "armor", effect: 65, mind: 40 },
        { name: "800kgくらいある全知全能", type: "armor", effect: 100, mind: 50 },
        { name: "毒のブラウン管", type: "poison", effect: 90, mind: -70 },
        { name: "アナログ火星", type: "weapon", effect: 65, mind: 20 },
        { name: "前衛的なTNT", type: "weapon", effect: 80, mind: 60 },
        { name: "べとべとティラノサウルス", type: "weapon", effect: 60, mind: -10 },
        { name: "ラスボスの曲", type: "weapon", effect: 75, mind: 50 },
        { name: "新品の焼きビーフン", type: "medicine", effect: 50, mind: 40 },
        { name: "カビの生えたつるぎまたは増殖する彁", type: "poison", effect: 85, mind: -60 },
        { name: "ほとんど違法のNumLockキー", type: "weapon", effect: 70, mind: 0 },
        { name: "一番いいテレホンカード", type: "armor", effect: 60, mind: 30 },
        { name: "反重力農産物", type: "medicine", effect: 70, mind: 60 },
        { name: "ウイルスに擬態した消えるGOOD判定", type: "poison", effect: 80, mind: -70 },
        { name: "えっちな寿司", type: "poison", effect: 75, mind: -30 },
        { name: "レトロなクッキー", type: "medicine", effect: 60, mind: 50 },
        { name: "幸運のエンチャントが付与された換気扇", type: "armor", effect: 65, mind: 40 },
        { name: "カスのアップデート", type: "poison", effect: 70, mind: -50 },
        { name: "原子炉キーの人類の技術を結集して作ったPUC", type: "weapon", effect: 95, mind: 80 },
        { name: "コンソメのカンピロバクター", type: "poison", effect: 85, mind: -60 },
        { name: "多目的リグレットカー", type: "armor", effect: 50, mind: 20 },
        { name: "禁断のカタコト脳筋", type: "poison", effect: 75, mind: -40 },
        { name: "プラズマ化した電子機器", type: "poison", effect: 80, mind: -60 },
        { name: "高圧市営バス", type: "armor", effect: 85, mind: 40 },
        { name: "宇宙古文書", type: "armor", effect: 60, mind: 30 },
        { name: "時計じかけの全部っぽい異臭を放つ個人差譜面", type: "weapon", effect: 70, mind: -50 },
        { name: "夢の地熱発電所", type: "armor", effect: 75, mind: 60 },
        { name: "猛一部キー", type: "weapon", effect: 55, mind: 30 },
        { name: "もこもこしたポケベル", type: "armor", effect: 20, mind: 20 },
        { name: "確変四天王", type: "weapon", effect: 75, mind: 40 },
        { name: "人類の技術を結集して作ったオレンジ", type: "medicine", effect: 90, mind: 80 },
        { name: "異常麺無しラーメン", type: "poison", effect: 80, mind: -40 },
        { name: "業務用の泣き虫ゼミ", type: "armor", effect: 45, mind: 15 },
        { name: "ダンジョン最深部で見つかったチョコ無しチョココロネ", type: "medicine", effect: 65, mind: 50 },
        { name: "アルミホイルの自動販売機", type: "weapon", effect: 35, mind: 5 },
        { name: "食用古文書", type: "medicine", effect: 50, mind: 30 },
        { name: "the Heavens 原子炉", type: "armor", effect: 90, mind: 80 },
        { name: "決戦のシャーペンの芯", type: "weapon", effect: 60, mind: 40 },
        { name: "伝票入れる筒状のアレを侍らせた一番いいお嬢様キー", type: "armor", effect: 70, mind: 60 },
        { name: "ぐにゃぐにゃツルハシ", type: "weapon", effect: 40, mind: 10 },
        { name: "暗黒の細菌", type: "poison", effect: 85, mind: -70 },
        { name: "ダークマターに擬態した増殖するタスクマネージャー", type: "poison", effect: 90, mind: -80 },
        { name: "最弱の気体", type: "armor", effect: 5, mind: 5 },
        { name: "つやつや割りばし", type: "weapon", effect: 20, mind: 0 },
        { name: "めり込んだエナジードリンク", type: "medicine", effect: 75, mind: 60 },
        { name: "ブランドものの虚無", type: "poison", effect: 60, mind: -40 },
        { name: "激辛全部", type: "poison", effect: 80, mind: -50 },
        { name: "2019年製液体", type: "poison", effect: 70, mind: -40 },
        { name: "燃え盛るアルミホイル系お嬢様", type: "weapon", effect: 85, mind: 60 },
        { name: "いにしえのペットボトル", type: "armor", effect: 40, mind: 20 },
        { name: "やばいGTX 380", type: "weapon", effect: 90, mind: 80 },
        { name: "電動オレンジ", type: "weapon", effect: 45, mind: 10 },
        { name: "3getした掛け軸", type: "armor", effect: 55, mind: 20 },
        { name: "土木学会田中賞を受賞した繝九Λ縺ｮ縺ｿ縺晄ｱ", type: "armor", effect: 80, mind: 70 },
        { name: "かわいいチョコ無しチョココロネ", type: "medicine", effect: 60, mind: 70 },
        { name: "100年に一度のゴルベーザ", type: "armor", effect: 70, mind: 60 },
        { name: "確変粒子加速器", type: "weapon", effect: 85, mind: 70 },
        { name: "破壊済みの全知全能", type: "armor", effect: 30, mind: -10 },
        { name: "つまようじに見せかけてえっちな水", type: "poison", effect: 75, mind: -60 },
        { name: "川を流れるカバのキーホルダー", type: "armor", effect: 35, mind: 15 },
        { name: "100均のRTX 6060", type: "weapon", effect: 40, mind: -5 },
        { name: "ヴィンテージ森羅万象", type: "armor", effect: 65, mind: 50 },
        { name: "800kgくらいあるメガネ", type: "armor", effect: 25, mind: -10 },
        { name: "チョコレートコーティング星のカービー", type: "medicine", effect: 80, mind: 80 },
        { name: "もこチキ謹製犯罪譜面", type: "weapon", effect: 90, mind: -70 },
        { name: "粗挽き全白皆伝", type: "weapon", effect: 70, mind: 40 },
        { name: "燃え盛る火星", type: "weapon", effect: 85, mind: 60 },
        { name: "最弱の化石", type: "armor", effect: 10, mind: -5 },
        { name: "焦げた3getロボ", type: "armor", effect: 45, mind: -20 },
        { name: "古代の原子力発電所", type: "armor", effect: 85, mind: 60 },
        { name: "強欲な閉じ忘れられた鉤括弧の片割れ", type: "weapon", effect: 55, mind: 0 },
        { name: "ムキムキピカグレ判定", type: "armor", effect: 60, mind: 50 },
        { name: "ゴルベーザオレオォ？", type: "poison", effect: 75, mind: -40 },
        { name: "アルミホイルのフロッピーディスク", type: "weapon", effect: 20, mind: 0 },
        { name: "真の物体", type: "armor", effect: 50, mind: 40 },
        { name: "束縛の呪いのエンチャントが付与された正十二面体", type: "armor", effect: 65, mind: 40 },
        { name: "えっちなオレオ", type: "poison", effect: 70, mind: -50 },
        { name: "凍った絵文字", type: "armor", effect: 40, mind: 20 },
        { name: "卵かけ因数分解", type: "medicine", effect: 75, mind: 70 },
        { name: "カスの農産物", type: "poison", effect: 60, mind: -40 },
        { name: "地獄の掛け軸", type: "armor", effect: 50, mind: -10 },
        { name: "デザイナーズiPodShuffle", type: "weapon", effect: 45, mind: 10 },
        { name: "賞味期限切れ牛乳パック", type: "poison", effect: 80, mind: -60 },
        { name: "耐火液体", type: "armor", effect: 75, mind: 60 },
        { name: "カビの生えた爪切り", type: "poison", effect: 70, mind: -50 },
        { name: "帯電金髪碧眼の美少女", type: "armor", effect: 85, mind: 70 },
        { name: "弓に擬態した強欲なiPodShuffle", type: "weapon", effect: 60, mind: 20 },
        { name: "あつあつヘリウム", type: "poison", effect: 90, mind: -70 },
        { name: "the Alpha 爪切り", type: "weapon", effect: 40, mind: 5 },
        { name: "異音がする健康保険証", type: "armor", effect: 30, mind: -20 },
        { name: "もこチキ型の鉛筆を虐げる群生する有象無象", type: "weapon", effect: 55, mind: 10 },
        { name: "当たり判定のないタンパク質", type: "poison", effect: 50, mind: -20 },
        { name: "2019年製腰", type: "armor", effect: 40, mind: 20 },
        { name: "陽電子粒子加速器", type: "weapon", effect: 85, mind: 70 },
        { name: "デザイナーズ森羅万象", type: "armor", effect: 65, mind: 60 },
        { name: "うますぎないつまようじ", type: "poison", effect: 60, mind: -40 },
        { name: "5日前の放射性廃棄物", type: "poison", effect: 95, mind: -90 },
        { name: "猛チョコレート", type: "medicine", effect: 80, mind: 70 },
        { name: "つやつやヘドロ", type: "poison", effect: 70, mind: -50 },
        { name: "卵かけ火星", type: "medicine", effect: 75, mind: 60 },
        { name: "4次元テレホンカード", type: "armor", effect: 60, mind: 40 },
        { name: "シュレディンガーのお嬢様キー", type: "armor", effect: 65, mind: 40 },
        { name: "最新式のTNT", type: "weapon", effect: 80, mind: 70 },
        { name: "謎の個人差譜面", type: "weapon", effect: 75, mind: -50 },
        { name: "プラチナの特異点", type: "weapon", effect: 70, mind: 50 },
        { name: "黄色のクリーム無しクリームパン", type: "poison", effect: 60, mind: -30 },
        { name: "無印の犯罪譜面", type: "weapon", effect: 70, mind: -50 },
        { name: "原子力パン無し食パン", type: "poison", effect: 85, mind: -60 },
        { name: "あすけんの女を黙らせられるクッキーキーの解き放たれし水", type: "medicine", effect: 90, mind: 80 },
        { name: "ゴルベーザ個人差譜面", type: "weapon", effect: 75, mind: -40 },
        { name: "束縛の呪いのエンチャントが付与されたマウスカーソル", type: "armor", effect: 55, mind: 20 },
        { name: "冷やしビーフジャーキー", type: "medicine", effect: 60, mind: 40 },
        { name: "ズゥキニーに擬態したティラノサウルス", type: "weapon", effect: 85, mind: 70 },
        { name: "消える絵文字", type: "poison", effect: 70, mind: -40 },
        { name: "存在しないダークマター", type: "armor", effect: 40, mind: -10 },
        { name: "ゴルベーザもこきー", type: "armor", effect: 65, mind: 50 },
        { name: "やわらかいダム", type: "armor", effect: 40, mind: -10 },
        { name: "かわいいズッキーニ", type: "medicine", effect: 60, mind: 70 },
        { name: "先進的なもこもこチキン", type: "medicine", effect: 70, mind: 60 },
        { name: "無限のエンチャントが付与された卵かけご飯", type: "medicine", effect: 100, mind: 90 },
        { name: "エンターキーメンサの最強の原子", type: "weapon", effect: 95, mind: 80 },
        { name: "カビの生えたカレー無しカレーパン", type: "poison", effect: 80, mind: -70 },
        { name: "再帰的一部キー", type: "armor", effect: 50, mind: 20 },
        { name: "透明なもこもこ", type: "armor", effect: 15, mind: 15 },
        { name: "燃え盛るサイコロ", type: "weapon", effect: 75, mind: 70 },
        { name: "ぐにゃぐにゃC18H27NO3", type: "poison", effect: 80, mind: -60 },
        { name: "カスの閉じ忘れられた鉤括弧の片割れ", type: "weapon", effect: 50, mind: 20 },
        { name: "異星の空き缶", type: "weapon", effect: 30, mind: 10 },
        { name: "the Ultimate 白いもの", type: "armor", effect: 70, mind: 50 },
        { name: "もこチキ謹製エキノコックス", type: "poison", effect: 90, mind: -80 },
        { name: "2032年製オノ", type: "weapon", effect: 70, mind: 50 },
        { name: "the Alpha タンパク質", type: "medicine", effect: 85, mind: 70 },
        { name: "木の森羅万象", type: "armor", effect: 60, mind: 40 },
        { name: "謎のズッキーニ", type: "medicine", effect: 75, mind: 50 },
        { name: "毒の壺", type: "poison", effect: 85, mind: -60 },
        { name: "放射性曲", type: "poison", effect: 75, mind: -50 },
        { name: "もこもこしたペットボトル", type: "armor", effect: 40, mind: 20 },
        { name: "個人差譜面メンサのアナログポップアップ広告", type: "weapon", effect: 70, mind: -40 },
        { name: "チョコレートまたは【令和最新版】もこもこ", type: "medicine", effect: 65, mind: 50 },
        { name: "愛妻ハンドスピナー", type: "armor", effect: 45, mind: 30 },
        { name: "束縛の呪いのエンチャントが付与された有象無象", type: "armor", effect: 60, mind: 40 },
        { name: "もこチキ型の黄グレ判定", type: "armor", effect: 55, mind: 35 },
        { name: "謎のもぎもぎフルーツ", type: "poison", effect: 75, mind: -40 },
        { name: "ときどき分裂するNumLockキー", type: "armor", effect: 50, mind: 20 },
        { name: "オーバークロックされた遠心分離機", type: "weapon", effect: 70, mind: 40 },
        { name: "バグったソフラン譜面", type: "weapon", effect: 80, mind: -50 },
        { name: "サンドピクチャーっぽい再帰的トマト", type: "medicine", effect: 70, mind: 55 },
        { name: "前衛的な🤯", type: "weapon", effect: 65, mind: 30 },
        { name: "すごいゲームボーイアドバンス", type: "armor", effect: 50, mind: 35 },
        { name: "やわらかいちいさなメダル", type: "armor", effect: 15, mind: 10 },
        { name: "地獄から来た重いもの", type: "weapon", effect: 75, mind: 60 },
        { name: "ポケットサイズノートパソコン", type: "armor", effect: 30, mind: 25 },
        { name: "超最高スーパーHAPPYクッキー", type: "medicine", effect: 80, mind: 70 },
        { name: "高反発クワ", type: "weapon", effect: 75, mind: 55 }
]